#--------------------------------------------------------------------------------
# Values for this workshop - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
workshop_repo   : "https://github.com/wvuhpc/06-13-2016-morgantown"
workshop_site   : "https://wvuhpc.github.io/06-13-2016-morgantown"
#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
swc_blog        : ""
swc_contact     : "help@hpc.wvu.edu"
swc_files       : "http://files.software-carpentry.org"
swc_github      : "http://github.com/wvuhpc"
swc_githubio    : ""
swc_installer   : "https://github.com/swcarpentry/windows-installer/releases/download/v0.3/SWCarpentryInstaller.exe"
swc_site        : "http://software-carpentry.org"
swc_twitter     : ""
swc_vm          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtSTZLQzF4aVB4NDQ&export=download"
swc_pre_survey  : ""
swc_post_survey : ""
#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [tools]
